services:
  bot:
    build: ./bot
    env_file:
      - .env
    depends_on:
      - db
    restart: always
    networks:
      - app-net

  db:
    image: postgres:15-alpine
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: always
    networks:
      - app-net

volumes:
  postgres_data:

networks:
  app-net:
    driver: bridge

